"""
Seller endpoints (spec 7.2): schema generation + CRUD + image upload +
category-suggestion autocomplete (phase 2).

Category suggestions are intentionally *not* a separate lookup table: they
are generated by grouping+counting the category_path values already on real
ads, so the suggestion list grows organically as more sellers post (a
seller's custom, LLM-unrecognized category becomes a suggestion for the
next seller with a similar item, per the phase-2 spec) with no extra
write path or promotion job needed.
"""
import uuid

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.api.deps import get_current_user
from app.core.cloudinary_client import CloudinaryNotConfigured, build_upload_signature
from app.core.config import get_settings
from app.db.session import get_db
from app.llm.client import generate_seller_schema
from app.models.ad import Ad
from app.models.ad_image import AdImage
from app.models.saved_ad import SavedAd
from app.models.user import User
from app.schemas.llm import SchemaGenerationResult

router = APIRouter(prefix="/api/ads", tags=["ads"])
settings = get_settings()

_ALLOWED_STATUSES = {"active", "sold", "expired", "deleted"}


class SchemaRequest(BaseModel):
    description: str


class CreateAdRequest(BaseModel):
    title: str
    description: str
    price: float
    category_path: str
    specs: dict
    excluded_category_paths: list[str] = []
    user_added_fields: list[str] = []


class UpdateAdRequest(BaseModel):
    title: str | None = None
    description: str | None = None
    price: float | None = None
    status: str | None = None  # active, sold, expired, deleted
    category_path: str | None = None
    specs: dict | None = None
    excluded_category_paths: list[str] | None = None
    user_added_fields: list[str] | None = None


class AttachImageRequest(BaseModel):
    url: str
    is_primary: bool = False


def _serialize_ad(ad: Ad, images: list[AdImage]) -> dict:
    return {
        "id": str(ad.id),
        "seller_id": str(ad.seller_id),
        "title": ad.title,
        "description": ad.description,
        "price": float(ad.price),
        "status": ad.status,
        "category_path": ad.category_path,
        "specs": ad.specs,
        "location": ad.location,
        "created_at": ad.created_at.isoformat() if ad.created_at else None,
        "images": [{"id": str(i.id), "url": i.url, "is_primary": i.is_primary} for i in images],
    }


@router.post("/schema", response_model=SchemaGenerationResult)
def generate_schema(payload: SchemaRequest, _user: User = Depends(get_current_user)):
    # TODO: read-through app.models.schema_cache before calling the LLM (spec 4.4).
    return generate_seller_schema(payload.description)


@router.get("/categories/suggest")
def suggest_categories(q: str = "", limit: int = 10, db: Session = Depends(get_db)):
    """Autocomplete for the 'add your own category' post-ad field, ranked by
    how often each category_path is already used across real ads."""
    stmt = (
        select(Ad.category_path, func.count().label("cnt"))
        .where(Ad.status != "deleted")
        .group_by(Ad.category_path)
        .order_by(func.count().desc())
        .limit(min(limit, 50))
    )
    if q:
        stmt = stmt.where(Ad.category_path.ilike(f"%{q}%"))
    rows = db.execute(stmt).all()
    return {"categories": [row[0] for row in rows]}


@router.post("", status_code=status.HTTP_201_CREATED)
def create_ad(payload: CreateAdRequest, user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    ad = Ad(
        id=uuid.uuid4(),
        seller_id=user.id,
        title=payload.title,
        description=payload.description,
        price=payload.price,
        category_path=payload.category_path,
        excluded_category_paths=payload.excluded_category_paths,
        specs=payload.specs,
        user_added_fields=payload.user_added_fields,
    )
    db.add(ad)
    db.commit()
    db.refresh(ad)
    # TODO: enqueue embedding generation (Celery) so `ad.embedding` gets populated (spec 4.3).
    return {"id": str(ad.id)}


@router.put("/{ad_id}")
def update_ad(
    ad_id: uuid.UUID,
    payload: UpdateAdRequest,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    ad = db.get(Ad, ad_id)
    if ad is None or ad.seller_id != user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Ad not found")

    data = payload.model_dump(exclude_unset=True)
    if "status" in data and data["status"] not in _ALLOWED_STATUSES:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"status must be one of {sorted(_ALLOWED_STATUSES)}",
        )
    for field, value in data.items():
        setattr(ad, field, value)
    db.commit()
    db.refresh(ad)
    images = db.query(AdImage).filter(AdImage.ad_id == ad_id).order_by(AdImage.order_index).all()
    return _serialize_ad(ad, images)


@router.delete("/{ad_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_ad(ad_id: uuid.UUID, user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    ad = db.get(Ad, ad_id)
    if ad is None or ad.seller_id != user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Ad not found")
    ad.status = "deleted"
    db.commit()


@router.post("/{ad_id}/upload-signature")
def get_upload_signature(ad_id: uuid.UUID, user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    """Hand the frontend a short-lived Cloudinary signature so it can upload
    the image bytes directly to Cloudinary (never through this backend)."""
    ad = db.get(Ad, ad_id)
    if ad is None or ad.seller_id != user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Ad not found")

    existing_count = db.query(AdImage).filter(AdImage.ad_id == ad_id).count()
    if existing_count >= settings.MAX_AD_IMAGES:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"This ad already has the maximum of {settings.MAX_AD_IMAGES} images",
        )
    try:
        return build_upload_signature(folder=f"lessmarket/ads/{ad_id}")
    except CloudinaryNotConfigured as exc:
        raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail=str(exc)) from exc


@router.post("/{ad_id}/images", status_code=status.HTTP_201_CREATED)
def attach_image(
    ad_id: uuid.UUID,
    payload: AttachImageRequest,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Record an already-uploaded Cloudinary image URL against this ad. Call
    after the browser's direct-to-Cloudinary upload (using the signature
    from POST .../upload-signature) succeeds."""
    ad = db.get(Ad, ad_id)
    if ad is None or ad.seller_id != user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Ad not found")

    count = db.query(AdImage).filter(AdImage.ad_id == ad_id).count()
    if count >= settings.MAX_AD_IMAGES:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"This ad already has the maximum of {settings.MAX_AD_IMAGES} images",
        )
    image = AdImage(
        id=uuid.uuid4(),
        ad_id=ad_id,
        url=payload.url,
        is_primary=payload.is_primary or count == 0,
        order_index=count,
    )
    db.add(image)
    db.commit()
    db.refresh(image)
    return {"id": str(image.id), "url": image.url, "is_primary": image.is_primary}


@router.delete("/{ad_id}/images/{image_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_image(
    ad_id: uuid.UUID,
    image_id: uuid.UUID,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    ad = db.get(Ad, ad_id)
    if ad is None or ad.seller_id != user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Ad not found")
    image = db.get(AdImage, image_id)
    if image is None or image.ad_id != ad_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Image not found")
    db.delete(image)
    db.commit()


@router.post("/{ad_id}/save", status_code=status.HTTP_204_NO_CONTENT)
def save_ad(ad_id: uuid.UUID, user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    ad = db.get(Ad, ad_id)
    if ad is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Ad not found")
    if db.get(SavedAd, (user.id, ad_id)) is None:
        db.add(SavedAd(user_id=user.id, ad_id=ad_id))
        db.commit()


@router.delete("/{ad_id}/save", status_code=status.HTTP_204_NO_CONTENT)
def unsave_ad(ad_id: uuid.UUID, user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    saved = db.get(SavedAd, (user.id, ad_id))
    if saved is not None:
        db.delete(saved)
        db.commit()


@router.get("/{ad_id}")
def get_ad(ad_id: uuid.UUID, db: Session = Depends(get_db)):
    ad = db.get(Ad, ad_id)
    if ad is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Ad not found")
    images = db.query(AdImage).filter(AdImage.ad_id == ad_id).order_by(AdImage.order_index).all()
    return _serialize_ad(ad, images)
